# .github/workflows/deploy-pages.yml
name: Deploy to GitHub Pages

permissions:
  contents: write # to commit to gh-pages
  pages: write # to push the site
  id-token: write # for pages auth

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VITE_WIP: 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5.0.0

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./dist

      - name: Deploy to Pages
        uses: actions/deploy-pages@v4.0.5
